---
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: NodePort
  selector:
    app: python-webapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30992
